dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.2.2

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2'

networks:
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
    
development:
  verify: False
  ganache-gui-2:
    verify: False
  mainnet-fork-dev:
    verify: False
    